In [1]:
liste = ['ABJC.ci.csv', 'BICC.ci.csv',
       'BNBC.ci.csv', 'BOABF.bf.csv', 'BOAC.ci.csv', 'BOAM.ml.csv',
       'BOAN.ne.csv', 'BOAS.sn.csv', 'CABC.ci.csv', 'CBIBF.bf.csv',
       'CFAC.ci.csv', 'CIEC.ci.csv', 'ECOC.ci.csv', 'ETIT.tg.csv',
       'NEIC.ci.csv', 'NSBC.ci.csv', 'NTLC.ci.csv', 'ONTBF.bf.csv',
       'PALC.ci.csv', 'PRSC.ci.csv', 'SAFC.ci.csv', 'SCRC.ci.csv',
       'SDCC.ci.csv', 'SGBC.ci.csv', 'SHEC.ci.csv', 'SICC.ci.csv',
       'SIVC.ci.csv', 'SLBC.ci.csv', 'SOGC.ci.csv', 'STAC.ci.csv',
       'STBC.ci.csv', 'UNLC.ci.csv', 'UNXC.ci.csv']

In [7]:
import os

AttributeError: module 'os' has no attribute 'getcd'

In [12]:
import pandas as pd
df = pd.read_csv("streamlit_app/Action.csv")

In [13]:
df

,Unnamed: 0.1,Unnamed: 0,ABJC.ci.csv,BICB.bj.csv,BICC.ci.csv,BNBC.ci.csv,BOABF.bf.csv,BOAC.ci.csv,BOAM.ml.csv,BOAN.ne.csv,...,SHEC.ci.csv,SICC.ci.csv,SIVC.ci.csv,SLBC.ci.csv,SOGC.ci.csv,STAC.ci.csv,STBC.ci.csv,UNLC.ci.csv,UNXC.ci.csv,date
0,0,0,1780,5495.0,15900.0,1000.0,4200,6010,2350,2770,...,950,3645.0,1000,14500,5390,585.0,9995.0,10275.0,400,01/04/2025
1,1,1,1750,5295.0,15400.0,1020.0,3250,6100,2500,2590,...,930,3290.0,1000,13800,5945,695.0,9695.0,18180.0,420,01/05/2025
2,2,2,2020,5600.0,10000.0,945.0,3400,3720,"1066,6666666666667","3309,375",...,860,3310.0,999,16820,3600,560.0,7195.0,6500.0,420,01/07/2024
3,3,3,1700,5350.0,16580.0,1150.0,3500,6100,3000,2455,...,1075,2825.0,500,11795,8150,770.0,17905.0,11000.0,580,01/07/2025
4,4,4,2230,5285.0,9740.0,1080.0,3275,4200,"1396,6666666666667",3250,...,810,3225.0,500,15500,3990,700.0,6700.0,18440.0,430,01/08/2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,242,242,2300,NaN,9740.0,1060.0,3400,4450,1800,3285,...,850,NaN,1000,NaN,3935,NaN,7500.0,NaN,420,30/09/2024
243,243,243,2240,NaN,10805.0,1090.0,3180,5695,2045,3200,...,880,NaN,510,NaN,4490,NaN,9950.0,NaN,450,30/10/2024
244,244,244,1795,NaN,NaN,1155.0,4245,4650,1710,2295,...,890,NaN,505,NaN,4490,NaN,6780.0,NaN,395,31/03/2025
245,245,245,2250,NaN,NaN,NaN,3250,6110,2400,2795,...,975,NaN,535,NaN,5500,NaN,7000.0,NaN,410,31/07/2024
246,246,246,2200,NaN,NaN,NaN,3390,3950,1400,"3271,875",...,850,NaN,500,NaN,3995,NaN,NaN,NaN,420,31/10/2024