In [ ]:
data = pd.read_excel(f"obligations.xlsx", engine="openpyxl")

In [40]:
data

,Periodicite,DateJouissance,DateFin,NbreDifferes,MontantEmis,NbrePeriodes,TauxInteretsNet,ValeurNominale,Unnamed: 8
0,80% 2024-2029,Semestriel,45643,47423,5,10000,10.00,6.80,10000.0
1,Semestriel,41072,42857,5,10000,10,6.25,10000.00,NaN
2,25% 2019-2024,Semestriel,43617,45399,5,10000,10.00,6.25,10000.0
3,Semestriel,40376,42831,5,10000,14,6.75,10000.00,NaN
4,Semestriel,41732,44200,5,10000,14,6.50,10000.00,NaN
5,10% 2017-2027,Semestriel,43047,46480,5,10000,20.00,6.10,10000.0
6,40% 2019-2026,Semestriel,43512,46213,5,10000,14.00,6.40,10000.0
7,50% 2021-2028,Semestriel,44483,46900,5,10000,14.00,6.50,10000.0
8,90% 2022-2029,Semestriel,44653,47119,5,10000,14.00,5.90,10000.0
9,50% 2024-2031,Semestriel,45341,47945,5,10000,14.00,6.50,10000.0
10,Semestriel,41271,42873,5,10000,10,6.25,10000.00,NaN
11,Semestriel,41064,42816,5,10000,10,6.25,10000.00,NaN
12,Semestriel,41207,43807,5,10000,14,5.95,10000.00,NaN
13,Semestriel,41645,44263,5,10000,14,5.95,10000.00,NaN
14,Semestriel,41092,42849,5,10000,10,6.25,10000.00,NaN
15,Semestriel,41126,43015,5,10000,10,6.50,10000.00,NaN
16,Semestriel,40829,42402,5,10000,10,6.50,10000.00,NaN
17,Semestriel,41068,44790,5,10000,20,6.10,10000.00,NaN
18,10% 2022-2037,Semestriel,44798,50119,5,10000,30.00,6.10,10000.0
19,Semestriel,41180,45353,5,10000,24,6.10,10000.00,NaN
20,Semestriel,41509,45195,5,10000,20,6.00,10000.00,NaN
21,Semestriel,41713,45557,5,10000,20,6.00,10000.00,NaN
22,85% 2015-2025,Semestriel,42358,45778,5,10000,20.00,5.85,10000.0
23,Semestriel,42406,46152,5,10000,20,5.85,10000.00,NaN
24,95% 2017-2029,Semestriel,42905,47266,5,10000,24.00,5.95,10000.0
25,95% 2018-2030,Semestriel,43179,47839,5,10000,24.00,5.95,10000.0
26,05% 2018-2033,Semestriel,43134,48723,5,10000,30.00,6.05,10000.0
27,50% 2024-2029,Semestriel,45344,47367,5,10000,10.00,6.50,10000.0
28,20% 2016-2023,Semestriel,42666,45180,5,10000,14.00,6.20,10000.0
29,20% 2022-2029,Semestriel,44713,47252,5,10000,14.00,6.20,10000.0
30,40% 2023-2030,Semestriel,44947,47534,5,10000,14.00,6.40,10000.0
31,50% 2023-2030,Semestriel,45196,47800,5,10000,14.00,6.50,10000.0
32,50% 2024-2034,Semestriel,45479,48986,5,10000,20.00,6.50,10000.0
33,00 % 2024-2031,Semestriel,45562,48185,5,10000,14.00,3.00,10000.0
34,55 % 2024-2031,Semestriel,45467,48177,5,10000,14.00,6.55,10000.0
35,35 % 2024-2029,Semestriel,45416,47143,5,10000,10.00,6.35,10000.0
36,25% 2023-2033,Semestriel,45217,48752,5,10000,20.00,7.25,10000.0
37,50% 2023-2038,Semestriel,45268,50641,5,10000,30.00,7.50,10000.0
38,Semestriel,44114,45882,5,10000,10,7.00,10000.00,NaN
39,Semestriel,44547,46079,5,10000,10,7.00,10000.00,NaN
40,40% 2023-2028,Semestriel,45246,46866,5,10000,10.00,6.40,10000.0
41,60% 2023-2030,Semestriel,45013,47601,5,10000,14.00,6.60,10000.0
42,Semestriel,44207,46760,5,10000,14,7.00,10000.00,NaN
43,25% 2024-2029,Semestriel,45524,47429,5,10000,10.00,7.25,10000.0
44,Semestriel,41558,43477,5,10000,12,6.75,10000.00,NaN
45,15% 2021-2028,Semestriel,44550,47077,5,10000,14.00,7.15,10000.0
46,Semestriel,40330,43001,5,10000,14,6.95,10000.00,NaN
47,Semestriel,40307,43018,5,10000,14,7.00,10000.00,NaN
48,60% 2020-2027,Semestriel,44141,46526,5,10000,14.00,6.60,10000.0
49,Semestriel,40133,42507,5,10000,14,7.00,10000.00,NaN

In [41]:
obligations = [
    {"Titre": "GSS BAOBAB 6,80% 2024-2029", "Periodicite": "Semestriel", "DateJouissance": "17/12/2024", "DateFin": "01/11/2029", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 10, "TauxInteretsNet": 6.8, "ValeurNominale": 10000},
    {"Titre": "BHB 6.25% 2012-2017", "Periodicite": "Semestriel", "DateJouissance": "12/06/2012", "DateFin": "02/05/2017", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 10, "TauxInteretsNet": 6.25, "ValeurNominale": 10000},
    {"Titre": "DIASPORA BONDS BHS 6,25% 2019-2024", "Periodicite": "Semestriel", "DateJouissance": "01/06/2019", "DateFin": "17/04/2024", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 10, "TauxInteretsNet": 6.25, "ValeurNominale": 10000},
    {"Titre": "BIDC 6.75% 2010-2017", "Periodicite": "Semestriel", "DateJouissance": "17/07/2010", "DateFin": "06/04/2017", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 14, "TauxInteretsNet": 6.75, "ValeurNominale": 10000},
    {"Titre": "BIDC-EBID 6.50% 2014-2021", "Periodicite": "Semestriel", "DateJouissance": "03/04/2014", "DateFin": "04/01/2021", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 14, "TauxInteretsNet": 6.5, "ValeurNominale": 10000},
    {"Titre": "BIDC-EBID 6,10% 2017-2027", "Periodicite": "Semestriel", "DateJouissance": "08/11/2017", "DateFin": "03/04/2027", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 20, "TauxInteretsNet": 6.1, "ValeurNominale": 10000},
    {"Titre": "BIDC-EBID 6,40% 2019-2026", "Periodicite": "Semestriel", "DateJouissance": "16/02/2019", "DateFin": "10/07/2026", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 14, "TauxInteretsNet": 6.4, "ValeurNominale": 10000},
    {"Titre": "BIDC-EBID 6,50% 2021-2028", "Periodicite": "Semestriel", "DateJouissance": "14/10/2021", "DateFin": "27/05/2028", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 14, "TauxInteretsNet": 6.5, "ValeurNominale": 10000},
    {"Titre": "BIDC-EBID 5,90% 2022-2029", "Periodicite": "Semestriel", "DateJouissance": "02/04/2022", "DateFin": "01/01/2029", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 14, "TauxInteretsNet": 5.9, "ValeurNominale": 10000},
    {"Titre": "BIDC-EBID GSS BOND 6,50% 2024-2031", "Periodicite": "Semestriel", "DateJouissance": "19/02/2024", "DateFin": "07/04/2031", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 14, "TauxInteretsNet": 6.5, "ValeurNominale": 10000},
    {"Titre": "BOA BURKINA FASO 6.25% 2012-2017", "Periodicite": "Semestriel", "DateJouissance": "28/12/2012", "DateFin": "18/05/2017", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 10, "TauxInteretsNet": 6.25, "ValeurNominale": 10000},
    {"Titre": "BOA COTE D IVOIRE 6.25% 2012-2017", "Periodicite": "Semestriel", "DateJouissance": "04/06/2012", "DateFin": "22/03/2017", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 10, "TauxInteretsNet": 6.25, "ValeurNominale": 10000},
    {"Titre": "BOAD 5.95% 2012-2019", "Periodicite": "Semestriel", "DateJouissance": "25/10/2012", "DateFin": "08/12/2019", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 14, "TauxInteretsNet": 5.95, "ValeurNominale": 10000},
    {"Titre": "BOAD 5.95% 2014-2021", "Periodicite": "Semestriel", "DateJouissance": "06/01/2014", "DateFin": "08/03/2021", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 14, "TauxInteretsNet": 5.95, "ValeurNominale": 10000},
    {"Titre": "BOA NIGER 6.25% 2012-2017", "Periodicite": "Semestriel", "DateJouissance": "02/07/2012", "DateFin": "24/04/2017", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 10, "TauxInteretsNet": 6.25, "ValeurNominale": 10000},
    {"Titre": "BOA SENEGAL 6.50% 2012-2017", "Periodicite": "Semestriel", "DateJouissance": "05/08/2012", "DateFin": "10/10/2017", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 10, "TauxInteretsNet": 6.5, "ValeurNominale": 10000},
    {"Titre": "CAA-BENIN 6.50% 2011-2016", "Periodicite": "Semestriel", "DateJouissance": "13/10/2011", "DateFin": "02/02/2016", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 10, "TauxInteretsNet": 6.5, "ValeurNominale": 10000},
    {"Titre": "CRRH-UEMOA 6.10% 2012-2022", "Periodicite": "Semestriel", "DateJouissance": "08/06/2012", "DateFin": "17/08/2022", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 20, "TauxInteretsNet": 6.1, "ValeurNominale": 10000},
    {"Titre": "CRRH-UEMOA 6,10% 2022-2037", "Periodicite": "Semestriel", "DateJouissance": "25/08/2022", "DateFin": "20/03/2037", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 30, "TauxInteretsNet": 6.1, "ValeurNominale": 10000},
    {"Titre": "CRRH-UEMOA 6.10% 2012-2024", "Periodicite": "Semestriel", "DateJouissance": "28/09/2012", "DateFin": "02/03/2024", "NbreDifferes": 5, "MontantEmis": 10000, "NbrePeriodes": 24, "TauxInteretsNet": 6.1, "ValeurNominale": 10000},

]

In [43]:
data = pd.DataFrame(obligations)

In [21]:
from Optimisation_Obl import construire_portefeuille

In [55]:
portefeuille, allocation, rendement = construire_portefeuille(df)

In [56]:
portefeuille

,Titre,Periodicite,DateJouissance,DateFin,NbreDifferes,MontantEmis,NbrePeriodes,TauxInteretsNet,ValeurNominale,Rendement1an
0,OBLIG Blanchet 8.71% 2020-2028,Semestriel,2020-05-18,2028-05-05,5,10000,16,8.71,10000,0.016593
1,OBLIG Ramos 6.84% 2024-2033,Semestriel,2024-02-03,2033-02-02,5,10000,18,6.84,10000,0.008025
2,OBLIG Moreau 5.95% 2019-2026,Semestriel,2019-12-25,2026-12-12,5,10000,14,5.95,10000,-0.008179

In [57]:
rendement

np.float64(0.016592764932088087)

In [58]:
allocation

array([1.00000000e+00, 3.80251386e-15, 0.00000000e+00])

In [52]:
from faker import Faker
import random
from datetime import timedelta
import pandas as pd

fake = Faker('fr_FR')

def generate_bond(index):
    taux = round(random.uniform(3.0, 9.0), 2)
    start_date = fake.date_between(start_date='-15y', end_date='today')
    years_duration = random.randint(3, 10)
    end_date = start_date.replace(year=start_date.year + years_duration)
    periodicite = "Semestriel"
    nbre_periodes = years_duration * 2
    montant_emis = 10000
    valeur_nominale = 10000

    titre = f"OBLIG {fake.company()} {taux}% {start_date.year}-{end_date.year}"
    
    return {
        "Titre": titre,
        "Periodicite": periodicite,
        "DateJouissance": start_date.strftime('%Y-%m-%d'),
        "DateFin": end_date.strftime('%Y-%m-%m'),
        "NbreDifferes": 5,
        "MontantEmis": montant_emis,
        "NbrePeriodes": nbre_periodes,
        "TauxInteretsNet": taux,
        "ValeurNominale": valeur_nominale
    }

# Générer 50 obligations
obligations = [generate_bond(i) for i in range(50)]

# Convertir en DataFrame
df = pd.DataFrame(obligations)

# Sauvegarde CSV avec séparateur virgule
df.to_csv("obligations_fictives.csv", index=False, sep=',')

# Aperçu

In [50]:
df

,Titre,Periodicite,DateJouissance,DateFin,NbreDifferes,MontantEmis,NbrePeriodes,TauxInteretsNet,ValeurNominale
0,OBLIG Loiseau Fernandez et Fils 8.59% 2023-2032,Semestriel,2023/12/09,2032/12/12,5,10000,18,8.59,10000
1,OBLIG Allain 7.35% 2016-2020,Semestriel,2016/12/28,2020/12/12,5,10000,8,7.35,10000
2,OBLIG Diaz Gomes S.A.R.L. 7.7% 2021-2030,Semestriel,2021/08/28,2030/08/08,5,10000,18,7.70,10000
3,OBLIG Robin 6.8% 2018-2025,Semestriel,2018/02/25,2025/02/02,5,10000,14,6.80,10000
4,OBLIG Pineau 4.76% 2022-2029,Semestriel,2022/05/25,2029/05/05,5,10000,14,4.76,10000
5,OBLIG Lombard 5.27% 2021-2027,Semestriel,2021/09/01,2027/09/09,5,10000,12,5.27,10000
6,OBLIG Hoareau 8.93% 2016-2026,Semestriel,2016/10/07,2026/10/10,5,10000,20,8.93,10000
7,OBLIG Laine S.A.R.L. 3.15% 2017-2020,Semestriel,2017/10/18,2020/10/10,5,10000,6,3.15,10000
8,OBLIG Leclercq 4.81% 2014-2019,Semestriel,2014/08/22,2019/08/08,5,10000,10,4.81,10000
9,OBLIG Léger 3.77% 2016-2020,Semestriel,2016/08/10,2020/08/08,5,10000,8,3.77,10000
10,OBLIG Vidal 7.84% 2015-2020,Semestriel,2015/01/04,2020/01/01,5,10000,10,7.84,10000
11,OBLIG Cordier 4.91% 2022-2032,Semestriel,2022/02/27,2032/02/02,5,10000,20,4.91,10000
12,OBLIG Fernandez et Fils 7.17% 2024-2030,Semestriel,2024/09/12,2030/09/09,5,10000,12,7.17,10000
13,OBLIG Launay SARL 3.49% 2019-2026,Semestriel,2019/05/03,2026/05/05,5,10000,14,3.49,10000
14,OBLIG Normand 5.69% 2018-2025,Semestriel,2018/02/20,2025/02/02,5,10000,14,5.69,10000
15,OBLIG Guibert S.A.R.L. 5.41% 2021-2029,Semestriel,2021/02/22,2029/02/02,5,10000,16,5.41,10000
16,OBLIG Imbert et Fils 5.13% 2018-2027,Semestriel,2018/12/05,2027/12/12,5,10000,18,5.13,10000
17,OBLIG Pages 7.51% 2022-2031,Semestriel,2022/06/14,2031/06/06,5,10000,18,7.51,10000
18,OBLIG Gilles 6.44% 2020-2024,Semestriel,2020/03/16,2024/03/03,5,10000,8,6.44,10000
19,OBLIG Seguin 5.61% 2024-2030,Semestriel,2024/08/29,2030/08/08,5,10000,12,5.61,10000
20,OBLIG Labbé 7.84% 2025-2035,Semestriel,2025/06/08,2035/06/06,5,10000,20,7.84,10000
21,OBLIG Grondin 6.81% 2011-2020,Semestriel,2011/06/02,2020/06/06,5,10000,18,6.81,10000
22,OBLIG Pages SARL 4.73% 2016-2022,Semestriel,2016/12/05,2022/12/12,5,10000,12,4.73,10000
23,OBLIG Jourdan Valette S.A.S. 3.58% 2021-2031,Semestriel,2021/02/21,2031/02/02,5,10000,20,3.58,10000
24,OBLIG Marchand Blanchard S.A.R.L. 5.98% 2011-2015,Semestriel,2011/03/11,2015/03/03,5,10000,8,5.98,10000
25,OBLIG Buisson Bigot SA 5.1% 2020-2025,Semestriel,2020/11/06,2025/11/11,5,10000,10,5.10,10000
26,OBLIG Lacroix 3.25% 2022-2031,Semestriel,2022/01/13,2031/01/01,5,10000,18,3.25,10000
27,OBLIG Pichon 7.08% 2013-2019,Semestriel,2013/12/04,2019/12/12,5,10000,12,7.08,10000
28,OBLIG Marie S.A.S. 6.14% 2011-2016,Semestriel,2011/07/04,2016/07/07,5,10000,10,6.14,10000
29,OBLIG Robert 7.06% 2020-2023,Semestriel,2020/09/10,2023/09/09,5,10000,6,7.06,10000
30,OBLIG Guyon S.A.R.L. 6.1% 2014-2019,Semestriel,2014/03/08,2019/03/03,5,10000,10,6.10,10000
31,OBLIG Picard 7.38% 2020-2025,Semestriel,2020/09/11,2025/09/09,5,10000,10,7.38,10000
32,OBLIG Benard 7.63% 2021-2031,Semestriel,2021/03/17,2031/03/03,5,10000,20,7.63,10000
33,OBLIG Gonzalez S.A.R.L. 6.27% 2017-2022,Semestriel,2017/07/21,2022/07/07,5,10000,10,6.27,10000
34,OBLIG Guérin SA 6.22% 2023-2029,Semestriel,2023/08/08,2029/08/08,5,10000,12,6.22,10000
35,OBLIG Leblanc Paris S.A.R.L. 5.13% 2019-2023,Semestriel,2019/04/22,2023/04/04,5,10000,8,5.13,10000
36,OBLIG Dos Santos 7.09% 2023-2029,Semestriel,2023/05/10,2029/05/05,5,10000,12,7.09,10000
37,OBLIG Da Silva S.A.S. 3.06% 2016-2023,Semestriel,2016/07/24,2023/07/07,5,10000,14,3.06,10000
38,OBLIG Leclercq Bonneau S.A. 3.92% 2020-2028,Semestriel,2020/07/03,2028/07/07,5,10000,16,3.92,10000
39,OBLIG Pons 7.07% 2012-2022,Semestriel,2012/04/01,2022/04/04,5,10000,20,7.07,10000
40,OBLIG Hamon Rossi S.A. 8.86% 2016-2019,Semestriel,2016/06/19,2019/06/06,5,10000,6,8.86,10000
41,OBLIG Gillet 5.47% 2023-2031,Semestriel,2023/12/27,2031/12/12,5,10000,16,5.47,10000
42,OBLIG Joseph SA 5.45% 2022-2026,Semestriel,2022/07/15,2026/07/07,5,10000,8,5.45,10000
43,OBLIG Moulin 3.87% 2019-2029,Semestriel,2019/10/20,2029/10/10,5,10000,20,3.87,10000
44,OBLIG Maurice S.A.R.L. 6.22% 2019-2029,Semestriel,2019/06/16,2029/06/06,5,10000,20,6.22,10000
45,OBLIG Merle 5.66% 2014-2022,Semestriel,2014/11/23,2022/11/11,5,10000,16,5.66,10000
46,OBLIG Bousquet 3.94% 2016-2019,Semestriel,2016/09/16,2019/09/09,5,10000,6,3.94,10000
47,OBLIG Hervé Teixeira SARL 4.92% 2015-2021,Semestriel,2015/08/17,2021/08/08,5,10000,12,4.92,10000
48,OBLIG Léger S.A.R.L. 3.27% 2016-2020,Semestriel,2016/01/14,2020/01/01,5,10000,8,3.27,10000
49,OBLIG Lévy 4.62% 2011-2021,Semestriel,2011/03/27,2021/03/03,5,10000,20,4.62,10000

In [75]:
import os

# Chemin du dossier contenant les fichiers
dossier = 'c:\\Users\\marcel.anee\\Desktop\\simul_portefeuil\\data_action'

# Préfixe à supprimer
prefixe = "cotation_"

# Parcours des fichiers dans le dossier
for nom_fichier in os.listdir(dossier):
    # Vérifie si le nom commence par "quotation_"
    if nom_fichier.startswith(prefixe):
        # Nouveau nom sans le préfixe
        nouveau_nom = nom_fichier[len(prefixe):]
        
        # Chemins complets
        ancien_chemin = os.path.join(dossier, nom_fichier)
        nouveau_chemin = os.path.join(dossier, nouveau_nom)
        
        # Renomme le fichier
        os.rename(ancien_chemin, nouveau_chemin)
        
        print(f"{nom_fichier} → {nouveau_nom}")

cotation_ABJC.ci.csv → ABJC.ci.csv
cotation_BICB.bj.csv → BICB.bj.csv
cotation_BICC.ci.csv → BICC.ci.csv
cotation_BNBC.ci.csv → BNBC.ci.csv
cotation_BOABF.bf.csv → BOABF.bf.csv
cotation_BOAC.ci.csv → BOAC.ci.csv
cotation_BOAM.ml.csv → BOAM.ml.csv
cotation_BOAN.ne.csv → BOAN.ne.csv
cotation_BOAS.sn.csv → BOAS.sn.csv
cotation_CABC.ci.csv → CABC.ci.csv
cotation_CBIBF.bf.csv → CBIBF.bf.csv
cotation_CFAC.ci.csv → CFAC.ci.csv
cotation_CIEC.ci.csv → CIEC.ci.csv
cotation_ECOC.ci.csv → ECOC.ci.csv
cotation_ETIT.tg.csv → ETIT.tg.csv
cotation_NEIC.ci.csv → NEIC.ci.csv
cotation_NSBC.ci.csv → NSBC.ci.csv
cotation_NTLC.ci.csv → NTLC.ci.csv
cotation_ONTBF.bf.csv → ONTBF.bf.csv
cotation_PALC.ci.csv → PALC.ci.csv
cotation_PRSC.ci.csv → PRSC.ci.csv
cotation_SAFC.ci.csv → SAFC.ci.csv
cotation_SCRC.ci.csv → SCRC.ci.csv
cotation_SDCC.ci.csv → SDCC.ci.csv
cotation_SGBC.ci.csv → SGBC.ci.csv
cotation_SHEC.ci.csv → SHEC.ci.csv
cotation_SICC.ci.csv → SICC.ci.csv
cotation_SIVC.ci.csv → SIVC.ci.csv
cotation_SLBC.ci.csv → SLBC.ci.csv
cotation_SOGC.ci.csv → SOGC.ci.csv
cotation_STAC.ci.csv → STAC.ci.csv
cotation_STBC.ci.csv → STBC.ci.csv
cotation_UNLC.ci.csv → UNLC.ci.csv
cotation_UNXC.ci.csv → UNXC.ci.csv

In [68]:
os.chdir('data_action/')

In [69]:
os.getcwd()

'c:\\Users\\marcel.anee\\Desktop\\simul_portefeuil\\data_action'

In [97]:
data = pd.read_csv(f'ABJC.ci.csv',sep=';')

In [98]:
data

     symbole        date  ouverture  haut   bas  cloture  volume
0    ABJC.ci  01/04/2025       1790  1790  1780     1780    4204
1    ABJC.ci  01/05/2025       1765  1765  1750     1750     919
2    ABJC.ci  01/07/2024       2005  2020  2005     2020    1991
3    ABJC.ci  01/07/2025       1725  1725  1700     1700     545
4    ABJC.ci  01/08/2024       2250  2250  2230     2230     661
..       ...         ...        ...   ...   ...      ...     ...
242  ABJC.ci  30/09/2024       2175  2300  2175     2300    1477
243  ABJC.ci  30/10/2024       2240  2240  2240     2240      11
244  ABJC.ci  31/03/2025       1795  1795  1795     1795    1213
245  ABJC.ci  31/07/2024       2295  2295  2250     2250    1145
246  ABJC.ci  31/10/2024       2200  2200  2200     2200     137

[247 rows x 7 columns]

In [103]:
df = pd.DataFrame()

In [104]:
df["date"]= data["date"]

In [105]:
data = pd.read_csv(f'ABJC.ci.csv',sep=';')

In [106]:
df['ABJC.ci'] = data['cloture']

In [108]:
data = pd.read_csv(f'BICC.ci.csv',sep=';')

In [109]:
df['BICC.ci'] = data['cloture']

In [110]:
df

           date  ABJC.ci  BICC.ci
0    01/04/2025     1780  15900.0
1    01/05/2025     1750  15400.0
2    01/07/2024     2020  10000.0
3    01/07/2025     1700  16580.0
4    01/08/2024     2230   9740.0
..          ...      ...      ...
242  30/09/2024     2300   9740.0
243  30/10/2024     2240  10805.0
244  31/03/2025     1795      NaN
245  31/07/2024     2250      NaN
246  31/10/2024     2200      NaN

[247 rows x 3 columns]

In [112]:
import os

#dossier = "chemin/vers/ton/dossier"

# Créer la liste vide
liste_fichiers_csv = []

# Parcourir le dossier
for fichier in os.listdir():
    if fichier.lower().endswith('.csv'):
        liste_fichiers_csv.append(fichier)

# Afficher la liste
liste_fichiers_csv

['ABJC.ci.csv',
 'BICB.bj.csv',
 'BICC.ci.csv',
 'BNBC.ci.csv',
 'BOABF.bf.csv',
 'BOAC.ci.csv',
 'BOAM.ml.csv',
 'BOAN.ne.csv',
 'BOAS.sn.csv',
 'CABC.ci.csv',
 'CBIBF.bf.csv',
 'CFAC.ci.csv',
 'CIEC.ci.csv',
 'ECOC.ci.csv',
 'ETIT.tg.csv',
 'NEIC.ci.csv',
 'NSBC.ci.csv',
 'NTLC.ci.csv',
 'ONTBF.bf.csv',
 'PALC.ci.csv',
 'PRSC.ci.csv',
 'SAFC.ci.csv',
 'SCRC.ci.csv',
 'SDCC.ci.csv',
 'SGBC.ci.csv',
 'SHEC.ci.csv',
 'SICC.ci.csv',
 'SIVC.ci.csv',
 'SLBC.ci.csv',
 'SOGC.ci.csv',
 'STAC.ci.csv',
 'STBC.ci.csv',
 'UNLC.ci.csv',
 'UNXC.ci.csv']

In [115]:
df = pd.DataFrame()
for titre in liste_fichiers_csv: 
    data = pd.read_csv(titre,sep=';')
    df[titre] = data['cloture']

In [121]:
data = pd.read_csv(f'SIVC.ci.csv',sep=';')

In [122]:
df["date"]= data["date"]

In [123]:
df

,ABJC.ci.csv,BICB.bj.csv,BICC.ci.csv,BNBC.ci.csv,BOABF.bf.csv,BOAC.ci.csv,BOAM.ml.csv,BOAN.ne.csv,BOAS.sn.csv,CABC.ci.csv,...,SHEC.ci.csv,SICC.ci.csv,SIVC.ci.csv,SLBC.ci.csv,SOGC.ci.csv,STAC.ci.csv,STBC.ci.csv,UNLC.ci.csv,UNXC.ci.csv,date
0,1780,5495.0,15900.0,1000.0,4200,6010,2350,2770,3935,1340,...,950,3645.0,1000,14500,5390,585.0,9995.0,10275.0,400,01/02/2010
1,1750,5295.0,15400.0,1020.0,3250,6100,2500,2590,4150,1380,...,930,3290.0,1000,13800,5945,695.0,9695.0,18180.0,420,01/03/2010
2,2020,5600.0,10000.0,945.0,3400,3720,"1066,6666666666667","3309,375","2593,3333333333335",1075,...,860,3310.0,999,16820,3600,560.0,7195.0,6500.0,420,01/04/2010
3,1700,5350.0,16580.0,1150.0,3500,6100,3000,2455,4280,1185,...,1075,2825.0,500,11795,8150,770.0,17905.0,11000.0,580,01/04/2025
4,2230,5285.0,9740.0,1080.0,3275,4200,"1396,6666666666667",3250,"3226,6666666666665",955,...,810,3225.0,500,15500,3990,700.0,6700.0,18440.0,430,01/05/2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242,2300,NaN,9740.0,1060.0,3400,4450,1800,3285,3750,1100,...,850,NaN,1000,NaN,3935,NaN,7500.0,NaN,420,25/03/2010
243,2240,NaN,10805.0,1090.0,3180,5695,2045,3200,3900,1100,...,880,NaN,510,NaN,4490,NaN,9950.0,NaN,450,25/03/2025
244,1795,NaN,NaN,1155.0,4245,4650,1710,2295,2725,1340,...,890,NaN,505,NaN,4490,NaN,6780.0,NaN,395,25/04/2025
245,2250,NaN,NaN,NaN,3250,6110,2400,2795,3950,1025,...,975,NaN,535,NaN,5500,NaN,7000.0,NaN,410,25/06/2025
246,2200,NaN,NaN,NaN,3390,3950,1400,"3271,875","3233,3333333333335",1100,...,850,NaN,500,NaN,3995,NaN,NaN,NaN,420,25/07/2024

In [126]:
os.chdir('..')

In [125]:
df.to_csv("Action.csv", index=False, sep=',')

In [119]:

import pandas as pd
import os

#dossier = "chemin/vers/ton/dossier"
liste_fichiers_csv = [f for f in os.listdir() if f.lower().endswith('.csv')]

# Dictionnaire compréhension : clé = nom fichier, valeur = nombre de lignes
nb_lignes_par_fichier = {
    titre: len(pd.read_csv(os.path.join(titre), sep=';'))
    for titre in liste_fichiers_csv
}

print(nb_lignes_par_fichier)

{'ABJC.ci.csv': 247, 'BICB.bj.csv': 54, 'BICC.ci.csv': 244, 'BNBC.ci.csv': 245, 'BOABF.bf.csv': 247, 'BOAC.ci.csv': 248, 'BOAM.ml.csv': 248, 'BOAN.ne.csv': 248, 'BOAS.sn.csv': 248, 'CABC.ci.csv': 247, 'CBIBF.bf.csv': 248, 'CFAC.ci.csv': 248, 'CIEC.ci.csv': 248, 'ECOC.ci.csv': 248, 'ETIT.tg.csv': 248, 'NEIC.ci.csv': 241, 'NSBC.ci.csv': 248, 'NTLC.ci.csv': 248, 'ONTBF.bf.csv': 248, 'PALC.ci.csv': 248, 'PRSC.ci.csv': 236, 'SAFC.ci.csv': 227, 'SCRC.ci.csv': 248, 'SDCC.ci.csv': 248, 'SGBC.ci.csv': 248, 'SHEC.ci.csv': 248, 'SICC.ci.csv': 165, 'SIVC.ci.csv': 305, 'SLBC.ci.csv': 195, 'SOGC.ci.csv': 248, 'STAC.ci.csv': 241, 'STBC.ci.csv': 246, 'UNLC.ci.csv': 158, 'UNXC.ci.csv': 248}

In [127]:
T

{'UNXC.ci.csv': 248}